'use client';
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uV9oPgP1qcl
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState } from "react";
import { useToast } from "./ui/use-toast";
import { Switch } from "./ui/switch";

export function ApplicationFormComponent() {
  const [file, setFile] = useState<File>();
  const [disabled, setDisabled] = useState(false);
  const [fileIntelMode, setFileIntelMode] = useState(false)
  const { toast } = useToast();
  
  
  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!file) return

    try {
      const data = new FormData()

      data.set('file', file);

      setDisabled(true);

      let type = !fileIntelMode ? "scan" : "intel"
      const res = await fetch(`/api/upload?type=${type}`, {
        method: 'POST',
        body: data
      })

      setDisabled(false);
      // clearInterval(progressInterval);
      
      const respBody = await res.json()
      // handle error
      if (!res.ok) throw new Error(respBody)
      else {
        toast({
          title: respBody?.data?.verdict,
          description: <div>
          <p>Score: {respBody?.data?.score}</p>
          <p>Categories: {respBody?.data?.category?.toString()}</p>
          {fileIntelMode ? <p>Hash: {respBody?.data?.hash}</p> : <></>}
          URL: {"url" in respBody?.data ? <a className="underline" href={respBody?.data?.url}> {respBody?.data?.url}</a> : <p>Not uploaded to storage</p>}
          </div>,
          className: respBody?.data?.verdict == "malicious" ? "bg-red-500 text-white" : (respBody?.data?.verdict == "suspicious" ? "bg-orange-400 text-white" : "bg-green-400 text-white")
        })
      }

    } catch (e) {
      console.error(e)
    }
  }

  return (
    <div key="1" className="mx-auto mt-8 min-h-screen justify-center items-center max-w-lg space-y-6">
      <div className="flex flex-row justify-between mb-32">
        <img src="/pangea-logo-rgb.png" className="w-1/3 h-1/3" />
        <p className="text-6xl">🤝</p>
        <img src="/reversinglabs_lg.png" className="w-1/3 h-1/3" />
      </div>
      <div className ="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Job Application - Amce Corp.</h1>
        <p className="text-zinc-500 dark:text-zinc-400">Fill out the form below to apply</p>
      </div>
      <form className="space-y-4" onSubmit={onSubmit}>
        <div className="space-y-2">
          <Label htmlFor="name">Full name</Label>
          <Input id="name" placeholder="Enter your full name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="you@example.com" required type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="phone">Phone Number</Label>
          <Input id="phone" placeholder="Enter your phone number" required type="tel" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="resume">Upload Resume</Label>
          <div className="border-2 border-dotted border-zinc-200 dark:border-zinc-700 p-6 rounded-md text-center cursor-pointer flex flex-col items-center justify-center space-y-3">
            <label
              className="w-full h-full flex flex-col items-center justify-center space-y-3 cursor-pointer"
              htmlFor="resume"
            >
            {!file ?
            <>
              <svg
                className=" text-3xl text-zinc-500 dark:text-zinc-400"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="17 8 12 3 7 8" />
                <line x1="12" x2="12" y1="3" y2="15" />
              </svg>
              <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
                Drag and drop your resume here, or
                <span className="underline cursor-pointer"> browse</span>
              </p>
            </>
            : (
              <>
              <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
                File Name: {file.name}
              </p>
              <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
                File Size: {file.size}
              </p>
              <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
                File Type: {file.type}
              </p>
              </>
            )}
              <Input className="sr-only" id="resume" type="file"
              onChange={(e) => setFile(e.target.files?.[0])} />
            </label>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <Switch id="file-intel-mode" onCheckedChange={e => {
            setFileIntelMode(!fileIntelMode);
          }} />
          <Label htmlFor="file-intel-mode">{fileIntelMode ? `File Intel` : `Deep File Scan`}</Label>
        </div>

        <Button className="w-full bg-purple-500 hover:bg-purple-700 disabled:bg-purple-400" type="submit" disabled={disabled}>
          Submit Application
          {/* Show preloader during request */}
          {disabled ? 
          <svg
            className=" ml-2 animate-spin h-5 w-5"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <line x1="12" x2="12" y1="2" y2="6" />
            <line x1="12" x2="12" y1="18" y2="22" />
            <line x1="4.93" x2="7.76" y1="4.93" y2="7.76" />
            <line x1="16.24" x2="19.07" y1="16.24" y2="19.07" />
            <line x1="2" x2="6" y1="12" y2="12" />
            <line x1="18" x2="22" y1="12" y2="12" />
            <line x1="4.93" x2="7.76" y1="19.07" y2="16.24" />
            <line x1="16.24" x2="19.07" y1="7.76" y2="4.93" />
          </svg> : <></>
          }
        </Button>
      </form>
    </div>
  )
}
